exports.statusCodes = {
    //200 onwards: general
    "200": "Page Not Found",
    "201": "Data generated successfully",
    "202": "Validation error",
    "203": "Unauthorized user",
    //300 onwards: user
    "300": "This email address already exists",
    "301": "User could not be created",
    "302": "User created successfully",
    "303": "User not found",
    "304": "Incorrect Password",
    "305": "Address added successfully",
    "306": "Address could not be added",
    "307": "Address removed successfully",
    "308": "Address could not be removed",
    "309": "Address not found",
    "310": "Address already exists",
    "311": "No items found. Cart is empty",
    "312": "Cart could not be cleared",
    //400 onwards: menu
    "401": "Empty menu",
    "402": "Dish could not be added",
    "403": "Dish added successfully",
    "404": "Dish name already exists",
    "405": "Dish not found",
    "406": "Dish deleted successfully",
    "407": "Dish could not be deleted",
    "408": "No categories found",
    "409": "Rating could not be added to the dish",
    "410": "Dish rated successfully",
    "411": "Rating stars must be between 0-5",
    //500 onwards: orders
    "500": "Orders not found",
    "501": "Order status could not be updated",
    "502": "Order status updated successfully",
    "503": "Feedback could not be added to the order",
    "504": "Feedback added successfully to the order",
    "505": "Dish successfully added to the cart",
    "506": "Dish could not be added to the cart",
    "507": "Order placed",
    "508": "Order could not be placed",
    "509": "Payment failed",
    "510": "Repeat order items have been successfully added to the cart",
    "511": "Payment successfull",
    "512": "Payment for this order has already been processed",
    //600 onwards : token
    "600": "Authorization header missing",
    "601": "Token Expired",
    "602": "Incorrect Token",
    "603": "Token not found or the token has expired",
    "604": "New access token generated",
}